import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { BrandMark, Field, PrimaryButton, SectionTitle } from '@/components/AppUI';
import { useQuotes } from '@/context/QuoteContext';
import { useColors } from '@/hooks/useColors';

export default function CustomersScreen() {
  const colors = useColors(); const { customers, quotes } = useQuotes(); const [search, setSearch] = useState('');
  const shown = useMemo(() => customers.filter((customer) => `${customer.name} ${customer.firm} ${customer.phone}`.toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr'))), [customers, search]);
  return <ScrollView style={[styles.page, { backgroundColor: colors.background }]} contentContainerStyle={styles.content}><BrandMark /><View style={styles.heading}><Text style={[styles.title, { color: colors.foreground }]}>Müşteriler</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Tüm müşteri bilgileri ve teklif geçmişleri.</Text></View><Field label="Müşteri ara" placeholder="İsim, firma veya telefon" value={search} onChangeText={setSearch} /><SectionTitle title={`${shown.length} müşteri`} action="Yeni müşteri" onAction={() => router.push('/customer')} />{shown.length === 0 ? <View style={[styles.empty, { backgroundColor: colors.card, borderColor: colors.border }]}><Feather name="users" size={25} color={colors.primary} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>Henüz müşteri yok</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Müşteri ekleyerek teklif geçmişini tek yerde takip edin.</Text><PrimaryButton label="Müşteri ekle" icon="user-plus" onPress={() => router.push('/customer')} /></View> : shown.map((customer) => { const history = quotes.filter((quote) => quote.customerId === customer.id || quote.customerName === customer.name); return <Pressable key={customer.id} onPress={() => router.push({ pathname: '/customer', params: { id: customer.id } })} style={[styles.customer, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.avatar, { backgroundColor: colors.secondary }]}><Text style={[styles.avatarText, { color: colors.primary }]}>{customer.name.slice(0, 1).toUpperCase()}</Text></View><View style={styles.main}><Text style={[styles.name, { color: colors.foreground }]}>{customer.name}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{customer.firm || customer.phone || 'Kişisel müşteri'} · {history.length} teklif</Text></View><Feather name="chevron-right" size={18} color={colors.mutedForeground} /></Pressable>; })}</ScrollView>;
}
const styles = StyleSheet.create({ page: { flex: 1 }, content: { padding: 20, paddingTop: 28, paddingBottom: 110, gap: 18 }, heading: { gap: 5 }, title: { fontSize: 28, fontWeight: '700', letterSpacing: -0.7 }, subtitle: { fontSize: 14, lineHeight: 20 }, empty: { borderWidth: 1, borderRadius: 18, padding: 22, alignItems: 'center', gap: 10 }, emptyTitle: { fontSize: 16, fontWeight: '700', textAlign: 'center' }, customer: { borderWidth: 1, borderRadius: 16, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 11 }, avatar: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontSize: 18, fontWeight: '700' }, main: { flex: 1, gap: 4 }, name: { fontSize: 14, fontWeight: '700' }, meta: { fontSize: 11 } });