import { Feather } from '@expo/vector-icons';
import React, { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { BrandMark, Field, PrimaryButton, SectionTitle } from '@/components/AppUI';
import { useQuotes } from '@/context/QuoteContext';
import { useColors } from '@/hooks/useColors';

export default function CustomersScreen() {
  const colors = useColors();
  const { quotes } = useQuotes();
  const [search, setSearch] = useState('');
  const customers = Array.from(new Set(quotes.map((quote) => quote.customerName).filter(Boolean))).filter((name) => name.toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr')));
  return <ScrollView style={[styles.page, { backgroundColor: colors.background }]} contentContainerStyle={styles.content}><BrandMark /><View style={styles.heading}><Text style={[styles.title, { color: colors.foreground }]}>Müşteriler</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Teklif geçmişiyle birlikte düzenli kayıtlarınız.</Text></View><Field label="Müşteri ara" placeholder="İsimle ara" value={search} onChangeText={setSearch} /><SectionTitle title={`${customers.length} müşteri`} />{customers.length === 0 ? <View style={[styles.empty, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.emptyIcon, { backgroundColor: colors.secondary }]}><Feather name="users" size={22} color={colors.primary} /></View><Text style={[styles.emptyTitle, { color: colors.foreground }]}>Henüz müşteri yok</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Yeni teklif oluşturduğunuzda müşterileriniz burada görünecek.</Text><PrimaryButton label="İlk teklifi oluştur" icon="plus" onPress={() => Alert.alert('Yeni teklif', 'Ana Sayfa sekmesinden Yeni Teklif Oluştur butonuna dokunun.')} /></View> : customers.map((customer) => { const customerQuotes = quotes.filter((quote) => quote.customerName === customer); return <View key={customer} style={[styles.customer, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.avatar, { backgroundColor: colors.secondary }]}><Text style={[styles.avatarText, { color: colors.primary }]}>{customer.slice(0, 1).toUpperCase()}</Text></View><View style={styles.main}><Text style={[styles.name, { color: colors.foreground }]}>{customer}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{customerQuotes.length} teklif · Son teklif {new Date(customerQuotes[0].createdAt).toLocaleDateString('tr-TR')}</Text></View><Feather name="chevron-right" size={18} color={colors.mutedForeground} /></View>; })}</ScrollView>;
}
const styles = StyleSheet.create({ page: { flex: 1 }, content: { padding: 20, paddingTop: 28, paddingBottom: 110, gap: 18 }, heading: { gap: 5 }, title: { fontSize: 28, fontWeight: '700', letterSpacing: -0.7 }, subtitle: { fontSize: 14, lineHeight: 20 }, empty: { borderWidth: 1, borderRadius: 18, padding: 22, alignItems: 'center', gap: 10 }, emptyIcon: { width: 48, height: 48, borderRadius: 16, justifyContent: 'center', alignItems: 'center' }, emptyTitle: { fontSize: 16, fontWeight: '700', textAlign: 'center' }, customer: { borderWidth: 1, borderRadius: 16, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 11 }, avatar: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontSize: 18, fontWeight: '700' }, main: { flex: 1, gap: 4 }, name: { fontSize: 14, fontWeight: '700' }, meta: { fontSize: 11 } });