import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { BrandMark, SectionTitle, StatusPill } from '@/components/AppUI';
import { formatCurrency, useQuotes } from '@/context/QuoteContext';
import { useColors } from '@/hooks/useColors';

export default function OffersScreen() {
  const colors = useColors();
  const { quotes } = useQuotes();
  const [filter, setFilter] = useState('Tümü');
  const [search, setSearch] = useState('');
  const filters = ['Tümü', 'Taslak', 'Gönderildi', 'Onaylandı', 'Reddedildi'];
  const shown = useMemo(() => quotes.filter((quote) => (filter === 'Tümü' || quote.status === filter) && (!search || `${quote.customerName} ${quote.title}`.toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr')))), [quotes, filter, search]);
  return <ScrollView style={[styles.page, { backgroundColor: colors.background }]} contentContainerStyle={styles.content}><BrandMark /><View style={styles.heading}><Text style={[styles.title, { color: colors.foreground }]}>Teklifler</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>{quotes.length} kayıt</Text></View><View style={[styles.search, { backgroundColor: colors.card, borderColor: colors.border }]}><Feather name="search" size={18} color={colors.mutedForeground} /><TextInput placeholder="Müşteri veya iş ara" placeholderTextColor={colors.mutedForeground} value={search} onChangeText={setSearch} style={[styles.searchInput, { color: colors.foreground }]} /></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filters.map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={[styles.filter, { backgroundColor: filter === item ? colors.primary : colors.card, borderColor: filter === item ? colors.primary : colors.border }]}><Text style={{ color: filter === item ? colors.primaryForeground : colors.mutedForeground, fontSize: 12, fontWeight: '700' }}>{item}</Text></Pressable>)}</ScrollView><SectionTitle title="Teklif geçmişi" action="Yeni teklif" onAction={() => router.push('/new-offer')} />{shown.length === 0 ? <View style={[styles.empty, { backgroundColor: colors.card, borderColor: colors.border }]}><Feather name="search" size={25} color={colors.primary} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>Teklif bulunamadı</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Arama veya filtreyi değiştirin.</Text></View> : shown.map((quote) => <Pressable key={quote.id} onPress={() => router.push({ pathname: '/preview', params: { id: quote.id } })} style={[styles.row, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.leading, { backgroundColor: colors.secondary }]}><Feather name="file-text" size={18} color={colors.primary} /></View><View style={styles.main}><Text style={[styles.name, { color: colors.foreground }]}>{quote.title}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{quote.customerName} · {quote.number} · {new Date(quote.createdAt).toLocaleDateString('tr-TR')}</Text></View><View style={styles.trailing}><StatusPill status={quote.status} /><Text style={[styles.price, { color: colors.foreground }]}>{formatCurrency(quote.total)}</Text></View></Pressable>)}</ScrollView>;
}
const styles = StyleSheet.create({ page: { flex: 1 }, content: { padding: 20, paddingTop: 28, paddingBottom: 110, gap: 18 }, heading: { gap: 4 }, title: { fontSize: 28, fontWeight: '700', letterSpacing: -0.7 }, subtitle: { fontSize: 14 }, search: { height: 50, borderRadius: 14, borderWidth: 1, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 10 }, searchInput: { flex: 1, fontSize: 14 }, filters: { gap: 8 }, filter: { borderWidth: 1, paddingVertical: 9, paddingHorizontal: 14, borderRadius: 30 }, row: { minHeight: 78, borderWidth: 1, borderRadius: 16, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 11 }, leading: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, main: { flex: 1, gap: 5 }, name: { fontSize: 14, fontWeight: '700' }, meta: { fontSize: 11 }, trailing: { alignItems: 'flex-end', gap: 7 }, price: { fontSize: 13, fontWeight: '700' }, empty: { alignItems: 'center', padding: 30, borderRadius: 18, borderWidth: 1, gap: 8 }, emptyTitle: { fontSize: 16, fontWeight: '700' } });