import { Feather } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import React, { useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { BrandMark, Field, PrimaryButton, SectionTitle } from '@/components/AppUI';
import { Company, useQuotes } from '@/context/QuoteContext';
import { useColors } from '@/hooks/useColors';

export default function SettingsScreen() {
  const colors = useColors();
  const { company, updateCompany } = useQuotes();
  const [draft, setDraft] = useState<Company>(company);
  const set = (key: keyof Company, value: string | number | boolean) => setDraft((current) => ({ ...current, [key]: value }));
  const save = async () => { await updateCompany(draft); Alert.alert('Kaydedildi', 'Firma bilgileriniz güncellendi.'); };
  const chooseLogo = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], base64: true, quality: 0.6 }); if (!result.canceled && result.assets[0]?.base64) set('logoDataUrl', `data:image/jpeg;base64,${result.assets[0].base64}`); };
  return <ScrollView style={[styles.page, { backgroundColor: colors.background }]} contentContainerStyle={styles.content}><BrandMark /><View style={styles.heading}><Text style={[styles.title, { color: colors.foreground }]}>Ayarlar</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Tekliflerinizde görünecek firma bilgileri.</Text></View><SectionTitle title="Firma bilgileri" /><Pressable onPress={() => void chooseLogo()} style={[styles.logoRow, { backgroundColor: colors.card, borderColor: colors.border }]}>{draft.logoDataUrl ? <Image source={{ uri: draft.logoDataUrl }} style={styles.logoImage} /> : <View style={[styles.logo, { backgroundColor: colors.primary }]}><Feather name="tool" size={21} color={colors.primaryForeground} /></View>}<View style={styles.main}><Text style={[styles.name, { color: colors.foreground }]}>Firma logosu</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>Teklif PDF'lerinde kullanılır</Text></View><Text style={[styles.change, { color: colors.primary }]}>Değiştir</Text></Pressable><Field label="Firma adı" value={draft.name} onChangeText={(value) => set('name', value)} /><Field label="Telefon" value={draft.phone} onChangeText={(value) => set('phone', value)} keyboardType="phone-pad" /><Field label="E-posta" value={draft.email} onChangeText={(value) => set('email', value)} keyboardType="email-address" autoCapitalize="none" /><Field label="Adres" value={draft.address} onChangeText={(value) => set('address', value)} multiline /><Field label="Vergi dairesi ve numarası" value={draft.taxInfo} onChangeText={(value) => set('taxInfo', value)} /><SectionTitle title="Teklif varsayılanları" /><View style={styles.twoCol}><View style={styles.half}><Field label="Varsayılan KDV %" value={String(draft.vatPercent)} onChangeText={(value) => set('vatPercent', Number(value) || 0)} keyboardType="decimal-pad" /></View><View style={styles.half}><Field label="Varsayılan kâr %" value={String(draft.profitPercent)} onChangeText={(value) => set('profitPercent', Number(value) || 0)} keyboardType="decimal-pad" /></View></View><View style={[styles.switchRow, { backgroundColor: colors.card, borderColor: colors.border }]}><View><Text style={[styles.name, { color: colors.foreground }]}>Koyu tema</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>Göz yormayan karanlık görünüm</Text></View><Switch value={draft.darkMode} onValueChange={(value) => set('darkMode', value)} trackColor={{ false: colors.border, true: colors.primary }} /></View><PrimaryButton label="Değişiklikleri kaydet" icon="check" onPress={save} /></ScrollView>;
}
const styles = StyleSheet.create({ page: { flex: 1 }, content: { padding: 20, paddingTop: 28, paddingBottom: 110, gap: 17 }, heading: { gap: 4 }, title: { fontSize: 28, fontWeight: '700', letterSpacing: -0.7 }, subtitle: { fontSize: 14, lineHeight: 20 }, logoRow: { borderWidth: 1, borderRadius: 16, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 12 }, logo: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, logoImage: { width: 42, height: 42, borderRadius: 14 }, main: { flex: 1, gap: 4 }, name: { fontSize: 14, fontWeight: '700' }, meta: { fontSize: 11 }, change: { fontSize: 12, fontWeight: '700' }, twoCol: { flexDirection: 'row', gap: 10 }, half: { flex: 1 }, switchRow: { minHeight: 64, borderRadius: 16, borderWidth: 1, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center' } });