import { Feather } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Field, PrimaryButton, SectionTitle, StatusPill } from '@/components/AppUI';
import { Customer, formatCurrency, useQuotes } from '@/context/QuoteContext';
import { useColors } from '@/hooks/useColors';

const emptyCustomer: Customer = { id: '', name: '', firm: '', phone: '', email: '', address: '', notes: '' };
export default function CustomerScreen() {
  const colors = useColors(); const { id } = useLocalSearchParams<{ id?: string }>(); const { customers, quotes, addCustomer, updateCustomer, deleteCustomer } = useQuotes();
  const existing = useMemo(() => customers.find((customer) => customer.id === id), [customers, id]);
  const [draft, setDraft] = useState<Customer>(existing ?? emptyCustomer);
  const set = (key: keyof Customer, value: string) => setDraft((current) => ({ ...current, [key]: value }));
  const history = quotes.filter((quote) => quote.customerId === existing?.id || quote.customerName === existing?.name);
  const save = async () => { if (!draft.name.trim()) { Alert.alert('Eksik bilgi', 'Müşteri adı zorunludur.'); return; } if (existing) await updateCustomer({ ...draft, id: existing.id }); else await addCustomer(draft); Alert.alert('Kaydedildi', 'Müşteri bilgileri güncellendi.'); router.back(); };
  const remove = () => Alert.alert('Müşteri silinsin mi?', 'Teklif geçmişi korunur; yalnızca müşteri kaydı silinir.', [{ text: 'Vazgeç', style: 'cancel' }, { text: 'Sil', style: 'destructive', onPress: () => void deleteCustomer(existing?.id ?? '').then(() => router.back()) }]);
  return <ScrollView style={[styles.page, { backgroundColor: colors.background }]} contentContainerStyle={styles.content}><View style={styles.top}><Pressable onPress={() => router.back()} style={styles.back}><Feather name="arrow-left" size={21} color={colors.foreground} /></Pressable><Text style={[styles.title, { color: colors.foreground }]}>{existing ? 'Müşteri detayı' : 'Yeni müşteri'}</Text></View><Field label="Ad soyad *" value={draft.name} onChangeText={(value) => set('name', value)} /><Field label="Firma" value={draft.firm} onChangeText={(value) => set('firm', value)} /><Field label="Telefon" value={draft.phone} onChangeText={(value) => set('phone', value)} keyboardType="phone-pad" /><Field label="E-posta" value={draft.email} onChangeText={(value) => set('email', value)} keyboardType="email-address" autoCapitalize="none" /><Field label="Adres" value={draft.address} onChangeText={(value) => set('address', value)} multiline /><Field label="Not" value={draft.notes} onChangeText={(value) => set('notes', value)} multiline /><PrimaryButton label="Müşteriyi kaydet" icon="check" onPress={() => void save()} />{existing && <><SectionTitle title={`Geçmiş teklifler (${history.length})`} />{history.length === 0 ? <Text style={{ color: colors.mutedForeground }}>Bu müşteriye ait teklif henüz yok.</Text> : history.map((quote) => <Pressable key={quote.id} onPress={() => router.push({ pathname: '/preview', params: { id: quote.id } })} style={[styles.quote, { backgroundColor: colors.card, borderColor: colors.border }]}><View><Text style={[styles.quoteTitle, { color: colors.foreground }]}>{quote.title}</Text><Text style={{ color: colors.mutedForeground, fontSize: 11 }}>{quote.number} · {new Date(quote.createdAt).toLocaleDateString('tr-TR')}</Text></View><View style={{ alignItems: 'flex-end', gap: 6 }}><StatusPill status={quote.status} /><Text style={{ color: colors.foreground, fontWeight: '700', fontSize: 12 }}>{formatCurrency(quote.total)}</Text></View></Pressable>)}<Pressable onPress={remove} style={styles.delete}><Feather name="trash-2" size={16} color={colors.destructive} /><Text style={{ color: colors.destructive, fontWeight: '700' }}>Müşteriyi sil</Text></Pressable></>}</ScrollView>;
}
const styles = StyleSheet.create({ page: { flex: 1 }, content: { padding: 20, paddingTop: 22, paddingBottom: 50, gap: 10 }, top: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 8 }, back: { width: 38, height: 38, justifyContent: 'center', alignItems: 'center' }, title: { fontSize: 24, fontWeight: '700' }, quote: { borderWidth: 1, borderRadius: 15, padding: 12, flexDirection: 'row', justifyContent: 'space-between', gap: 12 }, quoteTitle: { fontSize: 14, fontWeight: '700', marginBottom: 4 }, delete: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, padding: 16, marginTop: 10 } });