import { Feather } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { router, useLocalSearchParams } from 'expo-router';
import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { BrandMark, PrimaryButton, StatusPill } from '@/components/AppUI';
import { Quote, calculateTotals, formatCurrency, useQuotes } from '@/context/QuoteContext';
import { useColors } from '@/hooks/useColors';

export default function PreviewScreen() {
  const colors = useColors();
  const params = useLocalSearchParams<{ quoteDraft?: string; id?: string }>();
  const { company, quotes, addQuote, updateQuote, nextNumber } = useQuotes();
  const [saved, setSaved] = useState<Quote | null>(null);
  const draft = useMemo(() => params.quoteDraft ? JSON.parse(params.quoteDraft) as Omit<Quote, 'id' | 'number' | 'createdAt' | 'status'> : quotes.find((item) => item.id === params.id) ?? null, [params.quoteDraft, params.id, quotes]);
  useEffect(() => { if (!saved && draft && params.quoteDraft) { const quote = { ...draft, id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, number: nextNumber(), status: 'Taslak' as const, createdAt: new Date().toISOString() }; addQuote(quote).then(() => setSaved(quote)); } else if (!saved && draft && !params.quoteDraft) setSaved(draft as Quote); }, [draft]);
  if (!draft) return <View style={[styles.center, { backgroundColor: colors.background }]}><Text style={{ color: colors.foreground }}>Teklif bulunamadı.</Text></View>;
  const quote = saved ?? (draft as Quote);
  const totals = calculateTotals(quote);
  const html = `<html><body style="font-family:Arial;color:#10243E;padding:32px"><h1>${company.name}</h1><p>${company.phone} · ${company.email}</p><hr/><h2>Fiyat Teklifi</h2><p><b>Teklif no:</b> ${quote.number}<br/><b>Müşteri:</b> ${quote.customerName}<br/><b>İş:</b> ${quote.title}</p><p>${quote.description}</p><table style="width:100%;border-collapse:collapse"><tr><th style="text-align:left;border-bottom:1px solid #ddd;padding:8px">Kalem</th><th style="text-align:right;border-bottom:1px solid #ddd;padding:8px">Tutar</th></tr>${quote.items.map((item) => `<tr><td style="padding:8px;border-bottom:1px solid #eee">${item.name} (${item.quantity} ${item.unit})</td><td style="text-align:right;padding:8px;border-bottom:1px solid #eee">${formatCurrency(item.quantity * item.unitPrice)}</td></tr>`).join('')}</table><h2 style="text-align:right">Genel toplam: ${formatCurrency(totals.total)}</h2><p>Bu teklif ${quote.validDays} gün geçerlidir.</p></body></html>`;
  const makePdf = async () => { try { const result = await Print.printToFileAsync({ html }); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(result.uri, { mimeType: 'application/pdf', dialogTitle: 'Teklifi paylaş' }); else Alert.alert('PDF hazır', result.uri); } catch { Alert.alert('PDF oluşturulamadı', 'Lütfen tekrar deneyin.'); } };
  const markSent = async () => { const next = { ...quote, status: 'Gönderildi' as const }; await updateQuote(next); setSaved(next); Alert.alert('Teklif kaydedildi', 'Teklif gönderilmeye hazır olarak işaretlendi.'); };
  return <ScrollView style={[styles.page, { backgroundColor: colors.background }]} contentContainerStyle={styles.content}><View style={styles.top}><Pressable onPress={() => router.back()} style={styles.back}><Feather name="arrow-left" size={21} color={colors.foreground} /></Pressable><BrandMark small /><Text style={[styles.step, { color: colors.mutedForeground }]}>4 / 4</Text></View><View style={styles.heading}><Text style={[styles.title, { color: colors.foreground }]}>Teklif hazır</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Göndermeden önce son kez kontrol edin.</Text></View><View style={[styles.paper, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.paperHead}><BrandMark small /><StatusPill status={quote.status} /></View><View style={[styles.paperRule, { backgroundColor: colors.primary }]} /><Text style={[styles.quoteNo, { color: colors.mutedForeground }]}>{quote.number} · {new Date(quote.createdAt).toLocaleDateString('tr-TR')}</Text><Text style={[styles.paperTitle, { color: colors.foreground }]}>{quote.title}</Text><Text style={[styles.customer, { color: colors.mutedForeground }]}>{quote.customerName}{quote.phone ? ` · ${quote.phone}` : ''}</Text><Text style={[styles.description, { color: colors.foreground }]}>{quote.description}</Text><View style={styles.table}>{quote.items.map((item) => <View key={item.id} style={styles.tableRow}><Text style={[styles.itemName, { color: colors.foreground }]}>{item.name} <Text style={{ color: colors.mutedForeground }}>× {item.quantity} {item.unit}</Text></Text><Text style={[styles.itemPrice, { color: colors.foreground }]}>{formatCurrency(item.quantity * item.unitPrice)}</Text></View>)}</View><View style={[styles.divider, { backgroundColor: colors.border }]} /><View style={styles.summary}><Text style={[styles.summaryLabel, { color: colors.mutedForeground }]}>İşçilik + giderler</Text><Text style={[styles.summaryValue, { color: colors.foreground }]}>{formatCurrency(quote.labor + quote.transport + quote.other)}</Text><Text style={[styles.summaryLabel, { color: colors.mutedForeground }]}>KDV (%{quote.vatPercent})</Text><Text style={[styles.summaryValue, { color: colors.foreground }]}>{formatCurrency(totals.vat)}</Text><Text style={[styles.grandLabel, { color: colors.foreground }]}>Genel toplam</Text><Text style={[styles.grandValue, { color: colors.primary }]}>{formatCurrency(totals.total)}</Text></View><Text style={[styles.valid, { color: colors.mutedForeground }]}>Teklif geçerlilik süresi: {quote.validDays} gün</Text></View><View style={styles.actions}><PrimaryButton label="PDF oluştur ve paylaş" icon="share-2" onPress={makePdf} /><PrimaryButton label={quote.status === 'Gönderildi' ? 'Gönderildi' : 'Gönderildi olarak işaretle'} icon="send" onPress={markSent} secondary /></View></ScrollView>;
}
const styles = StyleSheet.create({ page: { flex: 1 }, content: { padding: 20, paddingTop: 20, paddingBottom: 50, gap: 14 }, center: { flex: 1, justifyContent: 'center', alignItems: 'center' }, top: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 }, back: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center' }, step: { marginLeft: 'auto', fontSize: 12, fontWeight: '700' }, heading: { gap: 5 }, title: { fontSize: 29, fontWeight: '700', letterSpacing: -0.8 }, subtitle: { fontSize: 14 }, paper: { borderWidth: 1, borderRadius: 19, padding: 18, gap: 10, shadowColor: '#10243E', shadowOpacity: 0.06, shadowRadius: 20, shadowOffset: { width: 0, height: 8 }, elevation: 2 }, paperHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, paperRule: { height: 3, borderRadius: 3, width: 46, marginTop: 2 }, quoteNo: { fontSize: 11, marginTop: 5 }, paperTitle: { fontSize: 21, fontWeight: '700', marginTop: 2 }, customer: { fontSize: 13 }, description: { fontSize: 13, lineHeight: 19, marginTop: 9 }, table: { marginTop: 8, gap: 11 }, tableRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 10 }, itemName: { fontSize: 12, flex: 1 }, itemPrice: { fontSize: 12, fontWeight: '700' }, divider: { height: 1, marginVertical: 4 }, summary: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8 }, summaryLabel: { width: '62%', fontSize: 12 }, summaryValue: { flex: 1, textAlign: 'right', fontSize: 12, fontWeight: '600' }, grandLabel: { width: '62%', fontSize: 15, fontWeight: '700', marginTop: 6 }, grandValue: { flex: 1, textAlign: 'right', fontSize: 20, fontWeight: '800', marginTop: 6 }, valid: { fontSize: 11, marginTop: 7 }, actions: { gap: 10 } });