name: Android Production AAB

on:
  push:
    branches:
      - main

jobs:
  build_android:
    name: Build Android production AAB
    type: build
    defaults:
      run:
        working_directory: ./artifacts/ustacep-ai
    params:
      platform: android
      profile: production
